### ISSUE TITLE
Create a wrapper for the attack graph initialization functions

### ISSUE THREAD

**Issue by andrewbwm** [mal-lang/mal-toolbox#21]
It is quite common to create an attack graph, attach attackers to it, and run the apriori calculations on it. As such we should create a graph_initialization wrapper function that takes the model and language graph as parameters and return the attack graph after all three steps have been performed.

**Comment by nkakouros** [comment]
I just made a comment (listed above) regarding this. Basically if the API is simplified as:

```
model = Model.load_from_file("tests/example_model.yml", lang_file)
attack_graph = AttackGraph(lang_file, model)
attack_graph.attach_attackers()
```

perhaps the need for the wrapper is no more?

**Comment by mrkickling** [comment]
Will look into this. Think I have understood the idea, but let me know if I got something wrong.

### Attach attackers / apriori calculations

If we want to attach attackers in AttackGraph by default, this feels like the best option to add to __init__:

`def __init__(self, lang_spec=None, model=None, attach_attackers=True)`

and attach the attackers if attach_attackers is set to True.

For the apriori calculations (calculate_viability_and_necessity), we could take the same approach.

### lang_file instead of lang spec / lang graph

For using filename of language instead of language specification I see two options:

1. Support giving lang_graph OR lang_file to the init of AttackGraph

`def __init__(self, lang: str | LanguageGraph, model, ...)`

and create the language graph (currently spec i guess) if lang is a filename (same could be done for Model to be consistent)

2. A separate wrapper function or class method that takes lang_file and creates the lang_graph and then creates an AttackGraph with lang_graph and model. Could also have an option to disable attach_attackers.

`def create_attack_graph(self, lang_file, model, ...) -> AttackGraph`

Here we could also use model_file instead for consistency.

Any preference here? Anything I seem to have misunderstood?

**Comment by nkakouros** [comment]
> 1. Support giving lang_graph OR lang_file to the init of AttackGraph

Why not support only lang_file?

**Comment by mrkickling** [comment]
Partly because it feels nice to allow for a modular approach where the user can split up the whole process in steps, but also: 
if you can give the LanguageGraph (or spec as now) to the AttackGraph, it will not have to recreate/compile the LanguageGraph/spec each time if several AttackGraphs you create use the same language. Might be wrong on the second point but let me know what you think.

**Comment by andrewbwm** [comment]
> Partly because it feels nice to allow for a modular approach where the user can split up the whole process in steps, but also: if you can give the LanguageGraph (or spec as now) to the AttackGraph, it will not have to recreate/compile the LanguageGraph/spec each time if several AttackGraphs you create use the same language. Might be wrong on the second point but let me know what you think.

We do not usually have multiple attack graphs using the same language graph/specification created at once.

However, we may want to have it still be an option as a non-file parameter in case we want to make modifications to the language graph/specification or model before creating the attack graph.

**Comment by andrewbwm** [comment]
After slightly more consideration I think I prefer the idea of having the constructor work with the language graph and instance model and having a wrapper that takes care of the filenames and the optional aspects such as attaching attackers and calculating viability and necessity.

**Comment by mrkickling** [comment]
Sounds good to me as well!

**Comment by mrkickling** [comment]
Thinking about where the wrapper should reside. It could be a class method in AttackGraph (create_from_lang_file or something), but since it involves Model and LanguageGraph (or LanguageSpecification) it might make sense to put it somewhere else outside of the attackgraph in some collection of maltoolbox helper functions. Any input?

Other questions: Do we want attach_attackers and apriori calculations to be run by default in the __init__ or AttackGraph?
