### ISSUE TITLE
Use converter from Literal to actual values when dumping model to json

### ISSUE THREAD

**Issue by mrkickling** [mal-lang/mal-toolbox#32]
When dumping yaml we use:

```python
contents = self.model_to_dict()

        yaml.add_multi_representer(
            LiteralValue,
            lambda dumper, data: dumper.represent_data(data._value),
            yaml.SafeDumper
        )

        fp = open(filename, 'w')
        yaml.dump(contents, fp, Dumper=yaml.SafeDumper)
```

We should have a similar method when dumping json. We could probably create our own `json.JSONEncoder` and use it in `json.dump(..., cls=OurJsonEncoder)` (see [json.JSONEncoder](https://docs.python.org/3/library/json.html#module-json)

Awaiting #13 to merge

**Comment by nkakouros** [comment]
Is there a need to support JSON in particular when dumping models? Do we expect to integrate with 3rd party tools? If not, why not make yaml the only supported format? Even if we encounter a json file somewhere whose format is compatible with what we support, we can still load it as yaml as yaml is a superset of json.

**Comment by andrewbwm** [comment]
There are some other people using the mal-toolbox with json models right now so it's best to still have it there just in case. I do think we may softly push towards yaml, because I really prefer the cleaner look, but I do not see any meaningful problems with supporting both. The explicit conversions I had to reintroduce to make it work with both aren't terrible anyway.
